### ISSUE TITLE
Heroku:  Starts then crashes

### ISSUE THREAD

**Issue by hirezl** [stevenleeg/geemusic#130]
I have geemusic deployed per directions on Heroku, when I look at the logs I get that it is starting then crashing.  I started looking at logs because no matter what I entered in testing screen on Amazon, I got "There was an error calling the remote endpoint"
2017-09-14T04:02:54.870961+00:00 heroku[web.1]: Starting process with command `python3 server.py`
2017-09-14T04:02:58.267896+00:00 app[web.1]: Traceback (most recent call last):
2017-09-14T04:02:58.267909+00:00 app[web.1]:   File "server.py", line 1, in <module>
2017-09-14T04:02:58.268050+00:00 app[web.1]:     from geemusic import app
2017-09-14T04:02:58.268053+00:00 app[web.1]:   File "/app/geemusic/__init__.py", line 13, in <module>
2017-09-14T04:02:58.268190+00:00 app[web.1]:     if str(environ['DEBUG_MODE']) is True:
2017-09-14T04:02:58.268208+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/os.py", line 669, in __getitem__
2017-09-14T04:02:58.268517+00:00 app[web.1]:     raise KeyError(key) from None
2017-09-14T04:02:58.268535+00:00 app[web.1]: KeyError: 'DEBUG_MODE'
2017-09-14T04:02:58.403218+00:00 heroku[web.1]: Process exited with status 1
2017-09-14T04:02:58.440566+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by huberf** [comment]
You'll need to run `heroku config:set DEBUG_MODE=False`.

I've submitted a PR to fix this issue in the documentation: https://github.com/stevenleeg/geemusic/pull/131

**Comment by hirezl** [comment]
Fixed, thank you!

**Comment by Mutate** [comment]
I am still getting the "There was an error calling the remote endpoint" error when trying to test in the amazon service simulator
